version: "3.8"
services:
  db:
    container_name: invoice-db
    image: postgres
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "db"
  cache:
    container_name: invoice-cache
    image: redis:alpine
    restart: always
    volumes:
      - cache:/data
    ports:
      - "6379:6379"

volumes:
  db:
    name: invoice-vol
  cache:
    driver: local
