import Gradient from "@/components/gradient";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import SnackbarProvider from "@components/snackbar/snackbar.provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "InvoiceX",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SnackbarProvider>{children}</SnackbarProvider>
      </body>
    </html>
  );
}
