import Gradient from "@/components/gradient";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "@/components/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "InvoiceX Docs",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <main className="relative flex min-h-screen flex-col items-center justify-center w-screen">
          <div className="fixed flex items-center justify-center">
            <Gradient
              className="absolute top-[-500px] opacity-[0.15] w-[1000px] h-[1000px]"
              conic
            />
          </div>
          <section className="absolute inset-0 z-10 min-h-screen p-10 pt-20 -md:px-3 max-w-[1000px] mx-auto leading-8">
            {children}
          </section>
        </main>
      </body>
    </html>
  );
}
